#ifndef LFLL_H
#define LFLL_H

#define LFLL_MAJOR_VERSION 0
#define LFLL_MINOR_VERSION 1
#define LFLL_PATCH_VERSION 0
#define LFLL_VERSION "LFLL_MAJOR_VERSION.LFLL_MINOR_VERSION.LFLL_PATCH_VERSION"




#endif // LFLL_H
