/*
The MIT License (MIT)

Copyright (c) 2013 Nicolas Pauss

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
#ifndef LFLLTUPLE_H
#define LFLLTUPLE_H

/**
 * This file is automatically generated by python/LFLLTupleGenerator.py
 */

#include <lfll/detail/LFLLTupleDetail.h>

/**
 * This tuple hold pointer of given values.
 * If you want a real tuple, you std::tuple (C++11) or boost::tuple
 */
template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33, class T34, class T35, class T36, class T37, class T38, class T39, class T40, class T41, class T42, class T43, class T44, class T45, class T46, class T47, class T48, class T49>
class LFLLTuple
{
    template <size_t I, class T_0, class T_1, class T_2, class T_3, class T_4, class T_5, class T_6, class T_7, class T_8, class T_9, class T_10, class T_11, class T_12, class T_13, class T_14, class T_15, class T_16, class T_17, class T_18, class T_19, class T_20, class T_21, class T_22, class T_23, class T_24, class T_25, class T_26, class T_27, class T_28, class T_29, class T_30, class T_31, class T_32, class T_33, class T_34, class T_35, class T_36, class T_37, class T_38, class T_39, class T_40, class T_41, class T_42, class T_43, class T_44, class T_45, class T_46, class T_47, class T_48, class T_49>
    friend
    typename detail::LFLLTupleValueTypes<I, T_0, T_1, T_2, T_3, T_4, T_5, T_6, T_7, T_8, T_9, T_10, T_11, T_12, T_13, T_14, T_15, T_16, T_17, T_18, T_19, T_20, T_21, T_22, T_23, T_24, T_25, T_26, T_27, T_28, T_29, T_30, T_31, T_32, T_33, T_34, T_35, T_36, T_37, T_38, T_39, T_40, T_41, T_42, T_43, T_44, T_45, T_46, T_47, T_48, T_49>::type*
    getLFLLTuple(LFLLTuple<T_0, T_1, T_2, T_3, T_4, T_5, T_6, T_7, T_8, T_9, T_10, T_11, T_12, T_13, T_14, T_15, T_16, T_17, T_18, T_19, T_20, T_21, T_22, T_23, T_24, T_25, T_26, T_27, T_28, T_29, T_30, T_31, T_32, T_33, T_34, T_35, T_36, T_37, T_38, T_39, T_40, T_41, T_42, T_43, T_44, T_45, T_46, T_47, T_48, T_49>& tuple);

    template <size_t I, class T_0, class T_1, class T_2, class T_3, class T_4, class T_5, class T_6, class T_7, class T_8, class T_9, class T_10, class T_11, class T_12, class T_13, class T_14, class T_15, class T_16, class T_17, class T_18, class T_19, class T_20, class T_21, class T_22, class T_23, class T_24, class T_25, class T_26, class T_27, class T_28, class T_29, class T_30, class T_31, class T_32, class T_33, class T_34, class T_35, class T_36, class T_37, class T_38, class T_39, class T_40, class T_41, class T_42, class T_43, class T_44, class T_45, class T_46, class T_47, class T_48, class T_49>
    friend
    const typename detail::LFLLTupleValueTypes<I, T_0, T_1, T_2, T_3, T_4, T_5, T_6, T_7, T_8, T_9, T_10, T_11, T_12, T_13, T_14, T_15, T_16, T_17, T_18, T_19, T_20, T_21, T_22, T_23, T_24, T_25, T_26, T_27, T_28, T_29, T_30, T_31, T_32, T_33, T_34, T_35, T_36, T_37, T_38, T_39, T_40, T_41, T_42, T_43, T_44, T_45, T_46, T_47, T_48, T_49>::type*
    getLFLLTuple(const LFLLTuple<T_0, T_1, T_2, T_3, T_4, T_5, T_6, T_7, T_8, T_9, T_10, T_11, T_12, T_13, T_14, T_15, T_16, T_17, T_18, T_19, T_20, T_21, T_22, T_23, T_24, T_25, T_26, T_27, T_28, T_29, T_30, T_31, T_32, T_33, T_34, T_35, T_36, T_37, T_38, T_39, T_40, T_41, T_42, T_43, T_44, T_45, T_46, T_47, T_48, T_49>& tuple);

public:
    static const size_t tuple_size = detail::LFLLTupleImpl<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49>::tuple_size;

public:
    LFLLTuple(T0* v0 = 0, T1* v1 = 0, T2* v2 = 0, T3* v3 = 0, T4* v4 = 0, T5* v5 = 0, T6* v6 = 0, T7* v7 = 0, T8* v8 = 0, T9* v9 = 0, T10* v10 = 0, T11* v11 = 0, T12* v12 = 0, T13* v13 = 0, T14* v14 = 0, T15* v15 = 0, T16* v16 = 0, T17* v17 = 0, T18* v18 = 0, T19* v19 = 0, T20* v20 = 0, T21* v21 = 0, T22* v22 = 0, T23* v23 = 0, T24* v24 = 0, T25* v25 = 0, T26* v26 = 0, T27* v27 = 0, T28* v28 = 0, T29* v29 = 0, T30* v30 = 0, T31* v31 = 0, T32* v32 = 0, T33* v33 = 0, T34* v34 = 0, T35* v35 = 0, T36* v36 = 0, T37* v37 = 0, T38* v38 = 0, T39* v39 = 0, T40* v40 = 0, T41* v41 = 0, T42* v42 = 0, T43* v43 = 0, T44* v44 = 0, T45* v45 = 0, T46* v46 = 0, T47* v47 = 0, T48* v48 = 0, T49* v49 = 0)
        : m_impl(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30, v31, v32, v33, v34, v35, v36, v37, v38, v39, v40, v41, v42, v43, v44, v45, v46, v47, v48, v49)
    {}

    template<size_t I>
    typename detail::LFLLTupleValueTypes<I, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49>::type*
    get()
    {
        typedef detail::LFLLTupleElementTypes<I, I, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49>
            ElementTypes;

        return static_cast<typename ElementTypes::type&>(m_impl).get();
    }

    template<size_t I>
    const typename detail::LFLLTupleValueTypes<I, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49>::type*
    get() const
    {
        typedef detail::LFLLTupleElementTypes<I, I, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49>
            ElementTypes;

        return static_cast<const typename ElementTypes::type&>(m_impl).get();
    }

    size_t size() const
    {
        return tuple_size;
    }

private:
    detail::LFLLTupleImpl<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49>
        m_impl;
};

// getLFLLTuple

template <size_t I, class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33, class T34, class T35, class T36, class T37, class T38, class T39, class T40, class T41, class T42, class T43, class T44, class T45, class T46, class T47, class T48, class T49>
inline
typename detail::LFLLTupleValueTypes<I, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49>::type*
getLFLLTuple(LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49>& tuple)
{
    typedef detail::LFLLTupleElementTypes<I, I, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49>
        ElementTypes;

    return static_cast<typename ElementTypes::type&>(tuple.m_impl).get();
}


template <size_t I, class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33, class T34, class T35, class T36, class T37, class T38, class T39, class T40, class T41, class T42, class T43, class T44, class T45, class T46, class T47, class T48, class T49>
inline
const typename detail::LFLLTupleValueTypes<I, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49>::type*
getLFLLTuple(const LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49>& tuple)
{
    typedef detail::LFLLTupleElementTypes<I, I, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49>
        ElementTypes;

    return static_cast<const typename ElementTypes::type&>(tuple.m_impl).get();
}

// LFLLTuple<T0, T1, ...> makeLFLLTuple(T0& v0, T1& v1, ...);


template <class T0>
inline
LFLLTuple<T0>
makeLFLLTuple(T0& v0)
{
    return LFLLTuple<T0>(&v0);
}


template <class T0, class T1>
inline
LFLLTuple<T0, T1>
makeLFLLTuple(T0& v0, T1& v1)
{
    return LFLLTuple<T0, T1>(&v0, &v1);
}


template <class T0, class T1, class T2>
inline
LFLLTuple<T0, T1, T2>
makeLFLLTuple(T0& v0, T1& v1, T2& v2)
{
    return LFLLTuple<T0, T1, T2>(&v0, &v1, &v2);
}


template <class T0, class T1, class T2, class T3>
inline
LFLLTuple<T0, T1, T2, T3>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3)
{
    return LFLLTuple<T0, T1, T2, T3>(&v0, &v1, &v2, &v3);
}


template <class T0, class T1, class T2, class T3, class T4>
inline
LFLLTuple<T0, T1, T2, T3, T4>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4)
{
    return LFLLTuple<T0, T1, T2, T3, T4>(&v0, &v1, &v2, &v3, &v4);
}


template <class T0, class T1, class T2, class T3, class T4, class T5>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5>(&v0, &v1, &v2, &v3, &v4, &v5);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6>(&v0, &v1, &v2, &v3, &v4, &v5, &v6);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30, T31& v31)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30, &v31);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30, T31& v31, T32& v32)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30, &v31, &v32);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30, T31& v31, T32& v32, T33& v33)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30, &v31, &v32, &v33);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33, class T34>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30, T31& v31, T32& v32, T33& v33, T34& v34)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30, &v31, &v32, &v33, &v34);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33, class T34, class T35>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30, T31& v31, T32& v32, T33& v33, T34& v34, T35& v35)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30, &v31, &v32, &v33, &v34, &v35);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33, class T34, class T35, class T36>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30, T31& v31, T32& v32, T33& v33, T34& v34, T35& v35, T36& v36)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30, &v31, &v32, &v33, &v34, &v35, &v36);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33, class T34, class T35, class T36, class T37>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30, T31& v31, T32& v32, T33& v33, T34& v34, T35& v35, T36& v36, T37& v37)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30, &v31, &v32, &v33, &v34, &v35, &v36, &v37);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33, class T34, class T35, class T36, class T37, class T38>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30, T31& v31, T32& v32, T33& v33, T34& v34, T35& v35, T36& v36, T37& v37, T38& v38)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30, &v31, &v32, &v33, &v34, &v35, &v36, &v37, &v38);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33, class T34, class T35, class T36, class T37, class T38, class T39>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30, T31& v31, T32& v32, T33& v33, T34& v34, T35& v35, T36& v36, T37& v37, T38& v38, T39& v39)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30, &v31, &v32, &v33, &v34, &v35, &v36, &v37, &v38, &v39);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33, class T34, class T35, class T36, class T37, class T38, class T39, class T40>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30, T31& v31, T32& v32, T33& v33, T34& v34, T35& v35, T36& v36, T37& v37, T38& v38, T39& v39, T40& v40)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30, &v31, &v32, &v33, &v34, &v35, &v36, &v37, &v38, &v39, &v40);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33, class T34, class T35, class T36, class T37, class T38, class T39, class T40, class T41>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30, T31& v31, T32& v32, T33& v33, T34& v34, T35& v35, T36& v36, T37& v37, T38& v38, T39& v39, T40& v40, T41& v41)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30, &v31, &v32, &v33, &v34, &v35, &v36, &v37, &v38, &v39, &v40, &v41);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33, class T34, class T35, class T36, class T37, class T38, class T39, class T40, class T41, class T42>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30, T31& v31, T32& v32, T33& v33, T34& v34, T35& v35, T36& v36, T37& v37, T38& v38, T39& v39, T40& v40, T41& v41, T42& v42)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30, &v31, &v32, &v33, &v34, &v35, &v36, &v37, &v38, &v39, &v40, &v41, &v42);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33, class T34, class T35, class T36, class T37, class T38, class T39, class T40, class T41, class T42, class T43>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30, T31& v31, T32& v32, T33& v33, T34& v34, T35& v35, T36& v36, T37& v37, T38& v38, T39& v39, T40& v40, T41& v41, T42& v42, T43& v43)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30, &v31, &v32, &v33, &v34, &v35, &v36, &v37, &v38, &v39, &v40, &v41, &v42, &v43);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33, class T34, class T35, class T36, class T37, class T38, class T39, class T40, class T41, class T42, class T43, class T44>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30, T31& v31, T32& v32, T33& v33, T34& v34, T35& v35, T36& v36, T37& v37, T38& v38, T39& v39, T40& v40, T41& v41, T42& v42, T43& v43, T44& v44)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30, &v31, &v32, &v33, &v34, &v35, &v36, &v37, &v38, &v39, &v40, &v41, &v42, &v43, &v44);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33, class T34, class T35, class T36, class T37, class T38, class T39, class T40, class T41, class T42, class T43, class T44, class T45>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30, T31& v31, T32& v32, T33& v33, T34& v34, T35& v35, T36& v36, T37& v37, T38& v38, T39& v39, T40& v40, T41& v41, T42& v42, T43& v43, T44& v44, T45& v45)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30, &v31, &v32, &v33, &v34, &v35, &v36, &v37, &v38, &v39, &v40, &v41, &v42, &v43, &v44, &v45);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33, class T34, class T35, class T36, class T37, class T38, class T39, class T40, class T41, class T42, class T43, class T44, class T45, class T46>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30, T31& v31, T32& v32, T33& v33, T34& v34, T35& v35, T36& v36, T37& v37, T38& v38, T39& v39, T40& v40, T41& v41, T42& v42, T43& v43, T44& v44, T45& v45, T46& v46)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30, &v31, &v32, &v33, &v34, &v35, &v36, &v37, &v38, &v39, &v40, &v41, &v42, &v43, &v44, &v45, &v46);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33, class T34, class T35, class T36, class T37, class T38, class T39, class T40, class T41, class T42, class T43, class T44, class T45, class T46, class T47>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30, T31& v31, T32& v32, T33& v33, T34& v34, T35& v35, T36& v36, T37& v37, T38& v38, T39& v39, T40& v40, T41& v41, T42& v42, T43& v43, T44& v44, T45& v45, T46& v46, T47& v47)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30, &v31, &v32, &v33, &v34, &v35, &v36, &v37, &v38, &v39, &v40, &v41, &v42, &v43, &v44, &v45, &v46, &v47);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33, class T34, class T35, class T36, class T37, class T38, class T39, class T40, class T41, class T42, class T43, class T44, class T45, class T46, class T47, class T48>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30, T31& v31, T32& v32, T33& v33, T34& v34, T35& v35, T36& v36, T37& v37, T38& v38, T39& v39, T40& v40, T41& v41, T42& v42, T43& v43, T44& v44, T45& v45, T46& v46, T47& v47, T48& v48)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30, &v31, &v32, &v33, &v34, &v35, &v36, &v37, &v38, &v39, &v40, &v41, &v42, &v43, &v44, &v45, &v46, &v47, &v48);
}


template <class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23, class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31, class T32, class T33, class T34, class T35, class T36, class T37, class T38, class T39, class T40, class T41, class T42, class T43, class T44, class T45, class T46, class T47, class T48, class T49>
inline
LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49>
makeLFLLTuple(T0& v0, T1& v1, T2& v2, T3& v3, T4& v4, T5& v5, T6& v6, T7& v7, T8& v8, T9& v9, T10& v10, T11& v11, T12& v12, T13& v13, T14& v14, T15& v15, T16& v16, T17& v17, T18& v18, T19& v19, T20& v20, T21& v21, T22& v22, T23& v23, T24& v24, T25& v25, T26& v26, T27& v27, T28& v28, T29& v29, T30& v30, T31& v31, T32& v32, T33& v33, T34& v34, T35& v35, T36& v36, T37& v37, T38& v38, T39& v39, T40& v40, T41& v41, T42& v42, T43& v43, T44& v44, T45& v45, T46& v46, T47& v47, T48& v48, T49& v49)
{
    return LFLLTuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49>(&v0, &v1, &v2, &v3, &v4, &v5, &v6, &v7, &v8, &v9, &v10, &v11, &v12, &v13, &v14, &v15, &v16, &v17, &v18, &v19, &v20, &v21, &v22, &v23, &v24, &v25, &v26, &v27, &v28, &v29, &v30, &v31, &v32, &v33, &v34, &v35, &v36, &v37, &v38, &v39, &v40, &v41, &v42, &v43, &v44, &v45, &v46, &v47, &v48, &v49);
}


#endif // LFLLTUPLE_H

